name: Daily Updates

env:
  GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
  GOOGLE_SPREADSHEET_ID_MAYORISTAS: ${{ secrets.GOOGLE_SPREADSHEET_ID_MAYORISTAS }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
  GOOGLE_SPREADSHEET_PAID_CHANNELS_REPORT: ${{ secrets.GOOGLE_SPREADSHEET_PAID_CHANNELS_REPORT }}
  
  # Nombre del spreadsheet para campaign report
  GOOGLE_SPREADSHEET_CAMPAIGN_REPORT_ID: ${{ secrets.GOOGLE_SPREADSHEET_CAMPAIGN_REPORT_ID }}

  PG_HOST: ${{ secrets.PG_HOST }}
  PG_PORT: ${{ secrets.PG_PORT }}
  PG_DATABASE: ${{ secrets.PG_DATABASE }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook
  schedule:
    # Ejecutar todos los días a las 00:00 UTC (ajusta según tus necesidades)
    - cron: '00 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install
          node daily-update.js